name: Move README.md on Issue Creation

on:
  issues:
    types: [opened]

jobs:
  move-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Move README.md from step1 to step2
      run: |
        mkdir -p step2
        mv step1/README.md step2/README.md

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add .
        git commit -m 'Move README.md from step1 to step2 on issue creation'
        git push
